# ----------------------------------------
# Created on: Wed May 31 08:34:57 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/pango_sim_libraries/usim"
vlog   "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/source/source/top_basketball.v" -work work
vlog   "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/source/source/fenpin.v" -work work
vlog   "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/source/source/counter.v" -work work
vlog   "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/source/shuxian.v" -work work
vlog   "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/source/fenpin_4Hz.v" -work work
vlog   "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/source/source/tb_top.v" -work work
vlog   "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/source/tb_counter.v" -work work
vlog   "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/source/tb_fenpin_4Hz.v" -work work
vlog   "C:/Users/lenovo/Documents/Pango_Design_Suite_Projects/project_shudian_wangjie/source/tb_shuxian.v" -work work

# ----------------------------------------
